name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - windows-msvc

        include:
          - toolchain: linux-gcc
            os: ubuntu-22.04
            build-script: "./cmake-b-release.sh"

          - toolchain: windows-msvc
            os: windows-latest
            build-script: "cmake-b-release.cmd"

    steps:
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "BUILD_DIR_BASE=build" > .env
        cat .env

    - name: Make build script executable (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: chmod +x cmake-b-release.sh read-env-file.sh

    - name: Build and Test using build script (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: ${{ matrix.build-script }}

    - name: Build and Test using build script (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: ${{ matrix.build-script }}

    - name: Verify build output
      run: |
        echo "Checking build output..."
        find . -name "build-*-release" -type d || echo "No release build directories found"
        find . -name "*.exe" -o -name "unit_tests" | head -10 || echo "No executables found"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.toolchain }}
        path: |
          build-*-release/bin/
          !build-*-release/**/*.pdb
          !build-*-release/**/*.ilk
        retention-days: 7
        if-no-files-found: warn

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Debug downloaded artifacts
      run: |
        echo "=== All downloaded files ==="
        find . -name "build-artifacts-*" -type d
        echo "=== Windows artifact contents ==="
        if [ -d "build-artifacts-windows-msvc" ]; then
          find build-artifacts-windows-msvc -type f | head -20
        else
          echo "No Windows artifacts directory found"
        fi

    - name: Generate release tag from current date
      id: get_version
      run: |
        TAG=$(date -u +"%Y.%m.%d.%H.%M")
        echo "version=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"

    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse "${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create release archive
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        # Create source code archive using git archive (avoids file change issues)
        echo "Creating source code archive"
        git archive --format=tar.gz --prefix=awwtools/ HEAD > awwtools-${{ steps.get_version.outputs.version }}-source.tar.gz

        mkdir -p release-files

        # List downloaded artifacts for debugging
        ls -la

        # Copy Windows binaries only
        if [ -d "build-artifacts-windows-msvc" ]; then
          echo "Found Windows artifacts"
          echo "Contents of build-artifacts-windows-msvc:"
          find build-artifacts-windows-msvc -type f | head -20

          # Copy the bin directory directly, flattening the structure
          if [ -d "build-artifacts-windows-msvc/build-windows-release/bin" ]; then
            cp -r build-artifacts-windows-msvc/build-windows-release/bin release-files/
            echo "Copied bin directory to release-files/"
          else
            echo "No build-windows-release/bin directory found"
            cp -r build-artifacts-windows-msvc/* release-files/
          fi

          echo "Contents of release-files after copy:"
          find release-files -type f | head -20

          # Delete logs folder if it exists
          rm -rf release-files/bin/logs

          echo "Contents of release-files/bin:"
          ls -la release-files/bin/ || echo "No bin directory found"
        else
          echo "Warning: No Windows artifacts found"
        fi

        # Create Windows binary archive only if directory exists and contains files
        if [ -d "release-files/bin" ] && [ "$(ls -A release-files/bin)" ]; then
          echo "Creating Windows binary archive"
          cd release-files
          zip -r ../awwtools-${{ steps.get_version.outputs.version }}-windows-x64-binaries.zip bin/
          cd ..
        else
          echo "ERROR: No Windows binary files found for release!"
          echo "This indicates the Windows build failed or artifacts were not uploaded properly."
          exit 1
        fi

        # Verify both archives were created
        if [ ! -f "awwtools-${{ steps.get_version.outputs.version }}-source.tar.gz" ]; then
          echo "ERROR: Source archive was not created!"
          exit 1
        fi

        if [ ! -f "awwtools-${{ steps.get_version.outputs.version }}-windows-x64-binaries.zip" ]; then
          echo "ERROR: Windows binary archive was not created!"
          exit 1
        fi

        # List created files
        ls -la awwtools-* || echo "No archives created"

    - name: Create Release
      if: steps.check_tag.outputs.exists == 'false'
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: AwwTools ${{ steps.get_version.outputs.version }}
        body: |
          ## AwwTools Release ${{ steps.get_version.outputs.version }}

          **Release Date:** ${{ github.event.head_commit.timestamp }}

          ### Contents:
          - 📦 **Source Code**: Complete source code archive
          - 🖥️ **Windows x64 Binaries**: Ready-to-run executables for Windows

          Build from commit: ${{ github.sha }}
        draft: false
        prerelease: false
        files: |
          awwtools-${{ steps.get_version.outputs.version }}-source.tar.gz
          awwtools-${{ steps.get_version.outputs.version }}-windows-x64-binaries.zip
