name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-22.04
            compiler: gcc

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
    - name: Install dependencies UBUNTU
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get update && sudo apt-get install -y build-essential

    
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure ubuntu-22.04
      if: matrix.os == 'ubuntu-22.04'
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Configure windows-latest
      if: matrix.os == 'windows-latest'
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C ${{ matrix.configuration }}
